### ISSUE TITLE
environment file for dependencies

### ISSUE THREAD

**Issue by Sachagobeyn** [cordmaur/WaterQuality#1]
The installation with the dependencies atm can be a little bit tedious, is it an option to add an environment-fil and install dependencies with conda and mamba in a seperate environment?:

```
conda env create -f environment.yml

conda activate waterquality
```

Content environment.yml file
```
name: waterquality
channels:
  - defaults
  - conda-forge
dependencies:
  - GDAL>=3.0.2
  - matplotlib>=3.1.2
  - PyPDF2>=1.26.0
  - scipy>=1.3.2
  - scikit-learn>=0.22
  - scikit-image>=0.16.2
  - numpy>=1.17
  - pip:
    - waterdetect>=1.5
```

**Comment by cordmaur** [comment]
Thank you @Sachagobeyn  for the suggestion. It's been added and the readme updated.
